#tasks.yaml
plot_structure_task:
  description: >
    Develop detailed plot structure from {outline} incorporating:
    - Opening scene framework
    - Inciting incident
    - Story launch sequence
    - Initial conflicts
  expected_output: >
    Detailed plot structure with scene progression and dramatic beats
  agent: act_one_plot_architect

scene_development_task:
  description: >
    Create scene breakdowns based on {outline}, {plot_structure}, and {world_parameters}
    including:
    - Scene objectives and formatting (INT/EXT. LOCATION TIME OF DAY)
    - Location details
    - Action sequences in present tense with visual focus
    - Scene transitions (FADE IN, CUT TO, etc.)
    - Dramatic moments
  expected_output: >
    Complete scene-by-scene breakdown with properly formatted setting, action descriptions,
    and scene transitions
  agent: act_one_scene_architect

dialogue_development_task:
  description: >
    Create character dialogue based on {outline}, {character_profiles}, and
    {scene_breakdown} considering:
    - Character voices with proper name capitalization
    - Parenthetical delivery notes
    - Off-screen (O.S.) and voiceover (V.O.) notation
    - Key conversations and relationship dynamics
    - Story revelations
  expected_output: >
    Scene-specific dialogue with industry-standard formatting and character interactions
  agent: act_one_dialogue_specialist

character_introduction_task:
  description: >
    Design character entrances and developments based on {outline}, {character_profiles},
    and {plot_structure} including:
    - First appearances
    - Character moments
    - Relationship establishments
    - Arc setups
  expected_output: >
    Character introduction sequences and development points
  agent: act_one_character_architect

world_building_task:
  description: >
    Establish story world based on {outline}, {setting_parameters}, and
    {genre_requirements} including:
    - Location descriptions
    - Environmental details
    - World rules
    - Atmosphere creation
  expected_output: >
    Detailed world-building elements and setting descriptions
  agent: act_one_world_builder

integration_task:
  description: >
    Combine all elements based on {outline}, {scene_components}, {character_profiles},
    and {world_parameters} ensuring:
    - Narrative flow
    - Pacing balance
    - Element consistency
    - Proper screenplay formatting (margins, font, spacing)
    - Quality standards
  expected_output: >
    Complete integrated Act One with consistent formatting and assembled elements
  agent: act_one_integration_manager

quality_review_task:
  description: >
    Review final Act One against {genre_requirements}, and
    {quality_requirements} checking:
    - Structure integrity
    - Character consistency
    - World cohesion
    - Dramatic effectiveness
  expected_output: >
    Quality assessment report with any needed revision recommendations
  agent: act_one_integration_manager

final_assembly_task:
  description: >
    Prepare final Act One document incorporating quality review feedback and ensuring:
    - Industry-standard formatting (1½-inch left margin, 1-inch others)
    - Courier New 12-point font
    - Proper page numbering
    - Element completion
    - Transition smoothness
    - Setup effectiveness
  expected_output: >
    Production-ready Act One script with professional formatting
  agent: act_one_integration_manager
