story_outline_task:
  description: >
    Create a detailed scene-by-scene outline incorporating:
    - {abstract}
    - {logline}
    - {central_message} 
    - {main_character_profile}
    - {supporting_characters_profile}
    - {outline}
    - {genre}
    Must break down the story into approximately 30 scenes while ensuring:
    - Clear narrative progression
    - Character development arcs
    - Proper pacing and story beats
    - Genre-appropriate elements
  expected_output: >
    A comprehensive scene-by-scene outline that forms the structural backbone of the screenplay
  agent: story_outline_architect

scene_writing_task:
  description: >
    Transform outline into properly formatted screenplay scenes incorporating:
    - Scene headings (INT/EXT. LOCATION - TIME)
    - Action descriptions in present tense
    - Character introductions in ALL CAPS
    - Natural dialogue with character voices
    - Setting descriptions and atmosphere
    Must ensure each scene:
    - Advances the plot
    - Develops characters
    - Builds atmosphere
    - Follows genre conventions
  expected_output: >
    Professional screenplay scenes that bring the story outline to life while following industry standards
  agent: scene_writer

dialogue_creation_task:
  description: >
    Create authentic dialogue based on:
    - {main_character_profile}
    - {supporting_characters_profile}
    Must ensure:
    - Distinct voice for each character
    - Natural conversation flow
    - Proper formatting (character names, parentheticals)
    - Dialogue advances plot and reveals character
  expected_output: >
    Well-crafted dialogue that reflects unique character voices while maintaining story progression
  agent: dialogue_specialist

continuity_tracking_task:
  description: >
    Monitor and maintain consistency across all scenes:
    - Plot progression
    - Character arcs and relationships
    - Setting details
    - Timeline continuity
    Must identify and flag any:
    - Plot holes
    - Character inconsistencies
    - Timeline errors
    - Setting discrepancies
  expected_output: >
    Detailed continuity report highlighting any issues requiring revision
  agent: continuity_manager

format_validation_task:
  description: >
    Verify proper screenplay formatting for:
    - Scene headings
    - Action descriptions
    - Character names and dialogue
    - Parentheticals and transitions
    Must ensure:
    - Industry-standard formatting
    - Proper page count (~30 pages)
    - Consistent spacing and layout
    - Professional presentation
  expected_output: >
    Format-compliant screenplay that meets industry standards
  agent: format_validator

integration_task:
  description: >
    Combine all elements while ensuring:
    - Coherent narrative flow
    - Consistent character development
    - Proper pacing
    - Genre requirements
    Must maintain:
    - Story integrity
    - Format standards
    - Target length
    - Professional quality
  expected_output: >
    Complete, polished screenplay that effectively tells the intended story
  agent: continuity_manager